version: 2
registries:
  github: # Define access so that Dependabot can access private repositories
    type: git
    url: https://github.com
    username: pmalek
    password: ${{secrets.PMALEK_PAT}}
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    registries:
      - github
